### ISSUE TITLE
[BUG] Scene loading can ruin performance

### ISSUE THREAD

**Issue by Doprez** [Nicogo1705/BepuPhysicIntegrationTest#3]
I am going to pin this in Stride as well since I think this is an issue with how Stride loads scenes.

When the startup scene in the gamesettings is the fountain scene the performance is flawless with the update time being 3-4ms.
![image](https://github.com/Nicogo1705/BepuPhysicIntegrationTest/assets/73259914/f2eb9954-12b0-4613-baa9-7b9ffd8f5d05)

when the scene is loaded through the SceneSelector.cs script it is more like 10-11ms
![image](https://github.com/Nicogo1705/BepuPhysicIntegrationTest/assets/73259914/987673d5-c145-4269-aa5b-0bfede20e95f)

script start up code
```
        public override void Start()
        {
            Game.Window.AllowUserResizing = true;
            //Game.Window.IsFullscreen = true;
            Game.Window.Title = "StrideGo";

            ((Stride.Games.GameBase)Game).MinimizedMinimumUpdateRate.MinimumElapsedTime = new TimeSpan(100000);
            ((Stride.Games.GameBase)Game).WindowMinimumUpdateRate.MinimumElapsedTime = new TimeSpan(100000);
            base.Start();
        }
```

scene switching code
```
        private void SetScene(UrlReference<Scene> sceneRef)
        {
            if (_last != null)
            {
                MainScene.Children.Clear();
                Content.Unload(_last);
                _last.Dispose();
            }

            if (sceneRef != null)
            {
                _last = Content.Load(sceneRef);
                MainScene.Children.Add(_last);
            }
        }
```

Im not sure where the problem lies but since the startup scene is performant I am assuming this is fixable and just needs more testing.

**Comment by Nicogo1705** [comment]
```csharp
((Stride.Games.GameBase)Game).MinimizedMinimumUpdateRate.MinimumElapsedTime = new TimeSpan(100000);
((Stride.Games.GameBase)Game).WindowMinimumUpdateRate.MinimumElapsedTime = new TimeSpan(100000);
```
As you may have noticed, I had put this in place to lock the FPS at 100 (thus a 10ms draw time). This is because without this, my graphics card was making unsettling noises.
