### ISSUE TITLE
[BUG] Gravity currently has no effect

### ISSUE THREAD

**Issue by Doprez** [Nicogo1705/BepuPhysicIntegrationTest#7]
When changing the gravity on the simulation component it does not change how the simulation works.

**Comment by Nicogo1705** [comment]
Got it! Here's a translated version:

For the gravity, we should develop a more robust system. With Bepu, gravity can be constant vec3(0, -9.8, 0), but it's flexible and can be set to anything else. Check out examples in the Bepu repository, such as [PerBodyGravityDemo.cs](https://github.com/bepu/bepuphysics2/blob/master/Demos/Demos/PerBodyGravityDemo.cs) or [PlanetDemo.cs](https://github.com/bepu/bepuphysics2/blob/master/Demos/Demos/PlanetDemo.cs).

**Comment by Nicogo1705** [comment]
https://github.com/Nicogo1705/BepuPhysicIntegrationTest/blob/b381c63fefc24074b46ac4d8cf48302749fe4fd9/BepuPhysicIntegrationTest/Integration/_Configurations/BepuSimulation.cs

Fixed it using Vec3 for now.
