### ISSUE TITLE
Character Controller

### ISSUE THREAD

**Issue by Doprez** [Nicogo1705/BepuPhysicIntegrationTest#8]
I will look into this when I have some time as I am starting to port my project over to Bepu. I want to add the character component from the [Bepu demo](https://github.com/bepu/bepuphysics2/blob/master/Demos/Demos/Characters/CharacterControllers.cs).

I need an FPS controller for my game so I will take a look into this when I have some time but I wanted to track it here to try and grow this repo.

This component should compare to the [Stride component](https://doc.stride3d.net/4.0/en/api/Stride.Physics.CharacterComponent.html) with the following properties:
- IsGrounded
- JumpSpeed
- MaxSlope (bonus)
- Orientation
- StepHeight (bonus)

and the following methods:
- Jump
- Move
- Rotate

**Comment by Nicogo1705** [comment]
https://github.com/Nicogo1705/BepuPhysicIntegrationTest/pull/13
